"""Add required Message columns

Revision ID: 556dc44c6cfd
Revises: 3f5ced59fffc
Create Date: 2025-10-02 09:21:17.583357

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '556dc44c6cfd'
down_revision = '3f5ced59fffc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
